---

## Layouts

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

### Styles

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false
