---

### Methods
Metrics/MethodLength:
  Max: 15

### Layouts

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  Enabled: false

  Layout/IndentationWidth:


### Styles

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false
