#!/bin/bash

echo 'Linking vimrc file...'
ln -s ~/dotfiles/.vimrc ~/.vimrc

echo 'Linking tmux configs file...'
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf

echo 'Linking eslint file...'
ln -s ~/dotfiles/.eslint.json ~/.eslint.json

echo 'Linking jscsrc file...'
ln -s ~/dotfiles/.jscsrc ~/.jscsrc

echo 'Linking .gitignore file...'
ln -s ~/dotfiles/.gitignore ~/.gitignore
git config --global core.excludesfile '~/.gitignore'

echo 'Installing Vundle...'
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo 'Installing molokai color theme...'
mkdir -p ~/.vim/colors
git clone https://github.com/tomasr/molokai.git ~/molokai
mv ~/molokai/colors/molokai.vim ~/.vim/colors
rm -rf ~/molokai

echo 'Installing homebrew...'
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Installing silver searcher...'
brew install the_silver_searcher

echo 'Installing fzf...'
brew install fzf
/usr/local/opt/fzf/install


