#!/bin/bash

echo 'Linking vimrc file...'
ln -s ~/dotfiles/.vimrc ~/.vimrc

echo 'Linking tmux configs file...'
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf

echo 'Linking eslint file...'
ln -s ~/dotfiles/.eslint.json ~/.eslint.json

echo 'Linking jscsrc file...'
ln -s ~/dotfiles/.jscsrc ~/.jscsrc

echo 'Linking .gitignore file...'
ln -s ~/dotfiles/.gitignore ~/.gitignore
git config --global core.excludesfile '~/.gitignore'

echo 'Linking .rspec file...'
ln -s ~/dotfiles/.rspec ~/.rspec

echo 'Linking .rubocop file...'
ln -s ~/dotfiles/.rubocop.yml ~/.rubocop.yml

echo 'Installing Vundle...'
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo 'Installing molokai color theme...'
mkdir -p ~/.vim/colors
git clone https://github.com/tomasr/molokai.git ~/molokai
mv ~/molokai/colors/molokai.vim ~/.vim/colors
rm -rf ~/molokai

echo 'Installing silver searcher...'
brew install the_silver_searcher

echo 'Installing fzf...'
brew install fzf
/usr/local/opt/fzf/install

echo 'Installing python3...'
brew install python3
brew postinstall python3

echo 'Installing yamllint...'
pip3 install yamllint

echo 'Installing NeoVim....'
brew install neovim

echo 'Configuring NeoVim...'
mkdir -p ~/.config/nvim
ln -s ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim

echo 'Installing vim-plug'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
