#!/bin/bash

set -euo pipeline

# MUST run from home directory!

echo 'Linking vimrc file...'
ln -s ~/dotfiles/.vimrc ~/.vimrc

echo 'Linking tmux configs file...'
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf

echo 'Linking .gitignore file...'
ln -s ~/dotfiles/.gitignore ~/.gitignore
git config --global core.excludesfile '~/.gitignore'

echo 'Linking .rspec file...'
ln -s ~/dotfiles/.rspec ~/.rspec

echo 'Linking .rubocop file...'
ln -s ~/dotfiles/.rubocop.yml ~/.rubocop.yml

echo 'Installing Vundle...'
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Apt Get update"
sudo apt-get upgrade -y && sudo apt-get update -y

echo 'Installing silver searcher, zsh and fzf'
sudo apt-get -y install silversearcher-ag fzf zsh

echo 'Installing vim-plug'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# https://asdf-vm.com/#/core-manage-asdf
echo 'Installing asdf version manager'
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1

echo 'Installing oh-my-zsh'
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo 'Copying over zsh themes'
cp dotfiles/zsh-themes/*.zsh-theme .oh-my-zsh/themes/

echo 'Copying over .zshrc'
cp dotfiles/.zshrc-ubuntu .zshrc
